# Generated by Django 5.1.3 on 2025-02-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
