# Generated by Django 5.1.3 on 2025-03-08 08:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
