# Generated by Django 5.1.3 on 2025-01-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_alter_category_slug_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cart', models.ManyToManyField(to='product.cart')),
            ],
        ),
    ]
