# Generated by Django 5.1.3 on 2025-01-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
