# Generated by Django 5.1.3 on 2025-01-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_checkout_tran_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
