# Generated by Django 5.1.3 on 2025-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_orderditem'),
        ('product', '0007_alter_category_slug_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderditem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderditem',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
