# Generated by Django 5.1.3 on 2025-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_orderditem_product_orderditem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderditem',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderditem',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderditem',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderditem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderditem',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
