# Generated by Django 5.1.3 on 2025-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_orderditem_address_orderditem_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderditem',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
