# Generated by Django 5.1.3 on 2025-02-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='payment.orderditem'),
        ),
    ]
