# Generated by Django 5.1.3 on 2025-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_shipping_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderditem',
            name='Shipping_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending'),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
