# Generated by Django 5.1.3 on 2025-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_orderditem_shipping_status_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
