# Generated by Django 5.1.3 on 2025-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_checkout_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
